# Generated by Django 3.2.20 on 2023-07-24 13:35

from django.db import migrations
from django.db.models import F, Subquery, OuterRef


def set_fixed_price(apps, schema_editor):
    Products = apps.get_model('foodcartapp', 'Products')
    Products.objects.filter(fixed_price=0).update(
        fixed_price=Subquery(Products.objects.filter(pk=OuterRef('pk')).values('product__price')[:1])
    )


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230724_1619'),
    ]

    operations = [
        migrations.RunPython(set_fixed_price),
    ]
