# Generated by Django 3.2.20 on 2023-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20230724_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'Обработать'), ('AS', 'Собрать'), ('TR', 'Доставить'), ('FN', 'Выполнен')], default='PR', max_length=2),
        ),
    ]
