# Generated by Django 3.2.20 on 2023-07-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_lastnam_ae467d_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['lastname', 'firstname', 'phonenumber', 'status'], name='foodcartapp_lastnam_a6d0b1_idx'),
        ),
    ]
