# Generated by Django 3.2.20 on 2023-07-26 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_comment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_lastnam_a6d0b1_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Звонок совершён'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Заказ создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставлен'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['lastname', 'firstname', 'phonenumber', 'status', 'created_at', 'called_at', 'delivered_at'], name='foodcartapp_lastnam_442aea_idx'),
        ),
    ]
