# Generated by Django 3.2.20 on 2023-07-26 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20230726_0946'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_lastnam_442aea_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('EL', 'Электронно'), ('CS', 'Наличностью')], default='CS', max_length=2),
        ),
        migrations.AlterField(
            model_name='products',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['lastname', 'firstname', 'phonenumber', 'status', 'created_at', 'called_at', 'delivered_at', 'payment_method'], name='foodcartapp_lastnam_2d75d3_idx'),
        ),
    ]
