# Generated by Django 3.2.20 on 2023-07-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Обработать'), (2, 'Собрать'), (3, 'Доставить'), (4, 'Выполнен')], default=1),
        ),
    ]
