# Generated by Django 3.2.20 on 2023-07-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20230728_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Координаты доставки: широта (latitude)'),
        ),
        migrations.AddField(
            model_name='order',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Координаты доставки: долгота (longitude)'),
        ),
    ]
